### PR TITLE
Addresses #27 - Adds delay between call to accel

### PR DESCRIPTION
**Pull request by aj-ptw**
Temporary fix till firmware is fixed

### CODE REVIEW

**Comment by KoroNiko** [comment]
Hello again and thanks for the fix! I can get the accelerometer data now. I edited my previous code with help from the accelerometer.js program, and I could still get the accelerometer data without using setTimeout() inside .then()

Here is my code:

```node

var nano = require('nanomsg');

var addr = 'tcp://0.0.0.0:5100';
var pub = nano.socket('pub');
pub.bind(addr);

const Ganglion = require('openbci-ganglion').Ganglion;
const ganglion = new Ganglion({verbose: true},
	(error) => {
		if (error) 
		{
			console.log("error", error);
		}
		else 
		{
			console.log("no error");
		}
	});


ganglion.on('accelerometer', 
	(accelData) => {
		console.log('accelData', accelData);
	})

ganglion.on('ganglionFound', 
	(peripheral) => {
		ganglion.connect(peripheral)
			ganglion.once('ready', () => {
				ganglion.accelStart().then(() => {
						ganglion.streamStart();
					});

				ganglion.on('sample', 
					(sample) => {
						// console.log(sample.accelData);
						console.log(sample.sampleNumber);
						strData = JSON.stringify(sample);
						pub.send(strData);
				});
			});
		});

ganglion.searchStart();

```

I'm getting the accelerometer data at pretty much the same rate(1 accelData/20 sampleNumber) as the accelerometer.js program.
Hope this helps!
Thanks again!

**Comment by aj-ptw** [comment]
Very interesting! So what is the difference if there is no delay?

**Comment by KoroNiko** [comment]
There is not a significant difference, I guess just a barely noticeable increase in speed

**Comment by aj-ptw** [comment]
Great, joel is working on a new release of the firmware and this bug has been patched and will be released! Thanks so much for helping to id this @KoroNiko

**Pull request merged**
